# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: stats.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import stats_pb2


class StatsBase(abc.ABC):

    @abc.abstractmethod
    async def GetStatGroupByCategory(self, stream):
        pass

    @abc.abstractmethod
    async def GetStatAsTable(self, stream):
        pass

    def __mapping__(self):
        return {
            '/stats.Stats/GetStatGroupByCategory': grpclib.const.Handler(
                self.GetStatGroupByCategory,
                grpclib.const.Cardinality.UNARY_UNARY,
                stats_pb2.LogItemQueryMessage,
                stats_pb2.ImageMessage,
            ),
            '/stats.Stats/GetStatAsTable': grpclib.const.Handler(
                self.GetStatAsTable,
                grpclib.const.Cardinality.UNARY_UNARY,
                stats_pb2.LogItemQueryMessage,
                stats_pb2.ImageMessage,
            ),
        }


class StatsStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetStatGroupByCategory = grpclib.client.UnaryUnaryMethod(
            channel,
            '/stats.Stats/GetStatGroupByCategory',
            stats_pb2.LogItemQueryMessage,
            stats_pb2.ImageMessage,
        )
        self.GetStatAsTable = grpclib.client.UnaryUnaryMethod(
            channel,
            '/stats.Stats/GetStatAsTable',
            stats_pb2.LogItemQueryMessage,
            stats_pb2.ImageMessage,
        )
