# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stats.proto',
  package='stats',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bstats.proto\x12\x05stats\"\x1b\n\x0cImageMessage\x12\x0b\n\x03res\x18\x01 \x01(\x0c\"K\n\x14LogMessageAggregated\x12\x11\n\tCreatedAt\x18\x01 \x01(\x03\x12\x0e\n\x06\x41mount\x18\x02 \x01(\x02\x12\x10\n\x08\x43\x61tegory\x18\x03 \x01(\t\"Q\n\x13LogItemQueryMessage\x12:\n\x15LogMessagesAggregated\x18\x01 \x03(\x0b\x32\x1b.stats.LogMessageAggregated2\xd9\x01\n\x05Stats\x12\x41\n\x0cGetMonthStat\x12\x1a.stats.LogItemQueryMessage\x1a\x13.stats.ImageMessage\"\x00\x12\x44\n\x0fGetCategoryStat\x12\x1a.stats.LogItemQueryMessage\x1a\x13.stats.ImageMessage\"\x00\x12G\n\x12GetMonthAmountStat\x12\x1a.stats.LogItemQueryMessage\x1a\x13.stats.ImageMessage\"\x00\x62\x06proto3')
)




_IMAGEMESSAGE = _descriptor.Descriptor(
  name='ImageMessage',
  full_name='stats.ImageMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='stats.ImageMessage.res', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=49,
)


_LOGMESSAGEAGGREGATED = _descriptor.Descriptor(
  name='LogMessageAggregated',
  full_name='stats.LogMessageAggregated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CreatedAt', full_name='stats.LogMessageAggregated.CreatedAt', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Amount', full_name='stats.LogMessageAggregated.Amount', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Category', full_name='stats.LogMessageAggregated.Category', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=126,
)


_LOGITEMQUERYMESSAGE = _descriptor.Descriptor(
  name='LogItemQueryMessage',
  full_name='stats.LogItemQueryMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='LogMessagesAggregated', full_name='stats.LogItemQueryMessage.LogMessagesAggregated', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=209,
)

_LOGITEMQUERYMESSAGE.fields_by_name['LogMessagesAggregated'].message_type = _LOGMESSAGEAGGREGATED
DESCRIPTOR.message_types_by_name['ImageMessage'] = _IMAGEMESSAGE
DESCRIPTOR.message_types_by_name['LogMessageAggregated'] = _LOGMESSAGEAGGREGATED
DESCRIPTOR.message_types_by_name['LogItemQueryMessage'] = _LOGITEMQUERYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageMessage = _reflection.GeneratedProtocolMessageType('ImageMessage', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEMESSAGE,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.ImageMessage)
  })
_sym_db.RegisterMessage(ImageMessage)

LogMessageAggregated = _reflection.GeneratedProtocolMessageType('LogMessageAggregated', (_message.Message,), {
  'DESCRIPTOR' : _LOGMESSAGEAGGREGATED,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.LogMessageAggregated)
  })
_sym_db.RegisterMessage(LogMessageAggregated)

LogItemQueryMessage = _reflection.GeneratedProtocolMessageType('LogItemQueryMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOGITEMQUERYMESSAGE,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.LogItemQueryMessage)
  })
_sym_db.RegisterMessage(LogItemQueryMessage)



_STATS = _descriptor.ServiceDescriptor(
  name='Stats',
  full_name='stats.Stats',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=212,
  serialized_end=429,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMonthStat',
    full_name='stats.Stats.GetMonthStat',
    index=0,
    containing_service=None,
    input_type=_LOGITEMQUERYMESSAGE,
    output_type=_IMAGEMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCategoryStat',
    full_name='stats.Stats.GetCategoryStat',
    index=1,
    containing_service=None,
    input_type=_LOGITEMQUERYMESSAGE,
    output_type=_IMAGEMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetMonthAmountStat',
    full_name='stats.Stats.GetMonthAmountStat',
    index=2,
    containing_service=None,
    input_type=_LOGITEMQUERYMESSAGE,
    output_type=_IMAGEMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATS)

DESCRIPTOR.services_by_name['Stats'] = _STATS

# @@protoc_insertion_point(module_scope)
