// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stats.proto

package stats

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ImageMessage struct {
	Res                  []byte   `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageMessage) Reset()         { *m = ImageMessage{} }
func (m *ImageMessage) String() string { return proto.CompactTextString(m) }
func (*ImageMessage) ProtoMessage()    {}
func (*ImageMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4756a0aec8b9d44, []int{0}
}

func (m *ImageMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageMessage.Unmarshal(m, b)
}
func (m *ImageMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageMessage.Marshal(b, m, deterministic)
}
func (m *ImageMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageMessage.Merge(m, src)
}
func (m *ImageMessage) XXX_Size() int {
	return xxx_messageInfo_ImageMessage.Size(m)
}
func (m *ImageMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ImageMessage proto.InternalMessageInfo

func (m *ImageMessage) GetRes() []byte {
	if m != nil {
		return m.Res
	}
	return nil
}

type LogItemMessage struct {
	CreatedAt            int64    `protobuf:"varint,1,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=Category,proto3" json:"Category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogItemMessage) Reset()         { *m = LogItemMessage{} }
func (m *LogItemMessage) String() string { return proto.CompactTextString(m) }
func (*LogItemMessage) ProtoMessage()    {}
func (*LogItemMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4756a0aec8b9d44, []int{1}
}

func (m *LogItemMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogItemMessage.Unmarshal(m, b)
}
func (m *LogItemMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogItemMessage.Marshal(b, m, deterministic)
}
func (m *LogItemMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogItemMessage.Merge(m, src)
}
func (m *LogItemMessage) XXX_Size() int {
	return xxx_messageInfo_LogItemMessage.Size(m)
}
func (m *LogItemMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LogItemMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LogItemMessage proto.InternalMessageInfo

func (m *LogItemMessage) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *LogItemMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogItemMessage) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *LogItemMessage) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type LogItemQueryMessage struct {
	LogItems             []*LogItemMessage `protobuf:"bytes,1,rep,name=LogItems,proto3" json:"LogItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LogItemQueryMessage) Reset()         { *m = LogItemQueryMessage{} }
func (m *LogItemQueryMessage) String() string { return proto.CompactTextString(m) }
func (*LogItemQueryMessage) ProtoMessage()    {}
func (*LogItemQueryMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4756a0aec8b9d44, []int{2}
}

func (m *LogItemQueryMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogItemQueryMessage.Unmarshal(m, b)
}
func (m *LogItemQueryMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogItemQueryMessage.Marshal(b, m, deterministic)
}
func (m *LogItemQueryMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogItemQueryMessage.Merge(m, src)
}
func (m *LogItemQueryMessage) XXX_Size() int {
	return xxx_messageInfo_LogItemQueryMessage.Size(m)
}
func (m *LogItemQueryMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LogItemQueryMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LogItemQueryMessage proto.InternalMessageInfo

func (m *LogItemQueryMessage) GetLogItems() []*LogItemMessage {
	if m != nil {
		return m.LogItems
	}
	return nil
}

func init() {
	proto.RegisterType((*ImageMessage)(nil), "stats.ImageMessage")
	proto.RegisterType((*LogItemMessage)(nil), "stats.LogItemMessage")
	proto.RegisterType((*LogItemQueryMessage)(nil), "stats.LogItemQueryMessage")
}

func init() { proto.RegisterFile("stats.proto", fileDescriptor_b4756a0aec8b9d44) }

var fileDescriptor_b4756a0aec8b9d44 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0x4d, 0xb7, 0x2d, 0xed, 0x74, 0x51, 0x99, 0xa2, 0x2c, 0x8b, 0x87, 0x65, 0x4f, 0x7b,
	0x2a, 0x58, 0x9f, 0x60, 0xa9, 0xb0, 0x16, 0xac, 0x60, 0x7c, 0x82, 0x88, 0xc3, 0x7a, 0xd9, 0x46,
	0x92, 0xa9, 0xd0, 0x47, 0xf5, 0x6d, 0x24, 0x69, 0xd2, 0x3f, 0xd7, 0xbd, 0xcd, 0x7c, 0xf9, 0x65,
	0xbe, 0x2f, 0x13, 0x98, 0x59, 0x56, 0x6c, 0x17, 0x3f, 0x46, 0xb3, 0xc6, 0x91, 0x6f, 0xca, 0x02,
	0xd2, 0x75, 0xa7, 0x5a, 0xda, 0x90, 0xb5, 0xaa, 0x25, 0xbc, 0x85, 0xc4, 0x90, 0xcd, 0x44, 0x21,
	0xaa, 0x54, 0xba, 0xb2, 0xfc, 0x85, 0xeb, 0x57, 0xdd, 0xae, 0x99, 0xba, 0xc8, 0x3c, 0xc0, 0x74,
	0x65, 0x48, 0x31, 0x7d, 0xd5, 0xec, 0xc9, 0x44, 0x9e, 0x04, 0x44, 0x18, 0xbe, 0xa9, 0x8e, 0xb2,
	0x41, 0x21, 0xaa, 0xa9, 0xf4, 0x35, 0xde, 0xc3, 0xb8, 0xee, 0xf4, 0x6e, 0xcb, 0x59, 0x52, 0x88,
	0x6a, 0x20, 0x43, 0x87, 0x39, 0x4c, 0x56, 0x8a, 0xa9, 0xd5, 0x66, 0x9f, 0x0d, 0x3d, 0x7f, 0xec,
	0xcb, 0x17, 0x98, 0x07, 0xdf, 0xf7, 0x1d, 0x99, 0x7d, 0x34, 0x7f, 0x84, 0x49, 0x90, 0x5d, 0xca,
	0xa4, 0x9a, 0x2d, 0xef, 0x16, 0x87, 0x77, 0x5d, 0xa6, 0x94, 0x47, 0x6c, 0xf9, 0x27, 0x60, 0xf4,
	0xe1, 0x10, 0xac, 0x21, 0x6d, 0x88, 0x37, 0x7a, 0xcb, 0xdf, 0x4e, 0xc0, 0xfc, 0xf2, 0xea, 0xb9,
	0x51, 0x3e, 0x0f, 0x67, 0xe7, 0xeb, 0x29, 0xaf, 0xf0, 0x19, 0x6e, 0x1a, 0xe2, 0x98, 0xb2, 0xef,
	0x94, 0x06, 0x30, 0x06, 0x39, 0xac, 0xa2, 0xe7, 0xa0, 0xcf, 0xb1, 0xff, 0xcd, 0xa7, 0xff, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xca, 0xe1, 0xe9, 0xbb, 0xdc, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatsClient is the client API for Stats service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatsClient interface {
	GetMonthStat(ctx context.Context, in *LogItemQueryMessage, opts ...grpc.CallOption) (*ImageMessage, error)
	GetCategoryStat(ctx context.Context, in *LogItemQueryMessage, opts ...grpc.CallOption) (*ImageMessage, error)
	GetMonthAmountStat(ctx context.Context, in *LogItemQueryMessage, opts ...grpc.CallOption) (*ImageMessage, error)
}

type statsClient struct {
	cc *grpc.ClientConn
}

func NewStatsClient(cc *grpc.ClientConn) StatsClient {
	return &statsClient{cc}
}

func (c *statsClient) GetMonthStat(ctx context.Context, in *LogItemQueryMessage, opts ...grpc.CallOption) (*ImageMessage, error) {
	out := new(ImageMessage)
	err := c.cc.Invoke(ctx, "/stats.Stats/GetMonthStat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) GetCategoryStat(ctx context.Context, in *LogItemQueryMessage, opts ...grpc.CallOption) (*ImageMessage, error) {
	out := new(ImageMessage)
	err := c.cc.Invoke(ctx, "/stats.Stats/GetCategoryStat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) GetMonthAmountStat(ctx context.Context, in *LogItemQueryMessage, opts ...grpc.CallOption) (*ImageMessage, error) {
	out := new(ImageMessage)
	err := c.cc.Invoke(ctx, "/stats.Stats/GetMonthAmountStat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServer is the server API for Stats service.
type StatsServer interface {
	GetMonthStat(context.Context, *LogItemQueryMessage) (*ImageMessage, error)
	GetCategoryStat(context.Context, *LogItemQueryMessage) (*ImageMessage, error)
	GetMonthAmountStat(context.Context, *LogItemQueryMessage) (*ImageMessage, error)
}

func RegisterStatsServer(s *grpc.Server, srv StatsServer) {
	s.RegisterService(&_Stats_serviceDesc, srv)
}

func _Stats_GetMonthStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogItemQueryMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetMonthStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stats.Stats/GetMonthStat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetMonthStat(ctx, req.(*LogItemQueryMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_GetCategoryStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogItemQueryMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetCategoryStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stats.Stats/GetCategoryStat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetCategoryStat(ctx, req.(*LogItemQueryMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_GetMonthAmountStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogItemQueryMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetMonthAmountStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stats.Stats/GetMonthAmountStat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetMonthAmountStat(ctx, req.(*LogItemQueryMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Stats_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stats.Stats",
	HandlerType: (*StatsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMonthStat",
			Handler:    _Stats_GetMonthStat_Handler,
		},
		{
			MethodName: "GetCategoryStat",
			Handler:    _Stats_GetCategoryStat_Handler,
		},
		{
			MethodName: "GetMonthAmountStat",
			Handler:    _Stats_GetMonthAmountStat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats.proto",
}
