// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stats.proto

package stats

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ImageMessage struct {
	Res                  []byte   `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageMessage) Reset()         { *m = ImageMessage{} }
func (m *ImageMessage) String() string { return proto.CompactTextString(m) }
func (*ImageMessage) ProtoMessage()    {}
func (*ImageMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4756a0aec8b9d44, []int{0}
}

func (m *ImageMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageMessage.Unmarshal(m, b)
}
func (m *ImageMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageMessage.Marshal(b, m, deterministic)
}
func (m *ImageMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageMessage.Merge(m, src)
}
func (m *ImageMessage) XXX_Size() int {
	return xxx_messageInfo_ImageMessage.Size(m)
}
func (m *ImageMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ImageMessage proto.InternalMessageInfo

func (m *ImageMessage) GetRes() []byte {
	if m != nil {
		return m.Res
	}
	return nil
}

type LogMessageAggregated struct {
	CreatedAt            int64    `protobuf:"varint,1,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Amount               float32  `protobuf:"fixed32,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogMessageAggregated) Reset()         { *m = LogMessageAggregated{} }
func (m *LogMessageAggregated) String() string { return proto.CompactTextString(m) }
func (*LogMessageAggregated) ProtoMessage()    {}
func (*LogMessageAggregated) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4756a0aec8b9d44, []int{1}
}

func (m *LogMessageAggregated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogMessageAggregated.Unmarshal(m, b)
}
func (m *LogMessageAggregated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogMessageAggregated.Marshal(b, m, deterministic)
}
func (m *LogMessageAggregated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogMessageAggregated.Merge(m, src)
}
func (m *LogMessageAggregated) XXX_Size() int {
	return xxx_messageInfo_LogMessageAggregated.Size(m)
}
func (m *LogMessageAggregated) XXX_DiscardUnknown() {
	xxx_messageInfo_LogMessageAggregated.DiscardUnknown(m)
}

var xxx_messageInfo_LogMessageAggregated proto.InternalMessageInfo

func (m *LogMessageAggregated) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *LogMessageAggregated) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *LogMessageAggregated) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type LogItemQueryMessage struct {
	LogMessagesAggregated []*LogMessageAggregated `protobuf:"bytes,1,rep,name=LogMessagesAggregated,proto3" json:"LogMessagesAggregated,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                `json:"-"`
	XXX_unrecognized      []byte                  `json:"-"`
	XXX_sizecache         int32                   `json:"-"`
}

func (m *LogItemQueryMessage) Reset()         { *m = LogItemQueryMessage{} }
func (m *LogItemQueryMessage) String() string { return proto.CompactTextString(m) }
func (*LogItemQueryMessage) ProtoMessage()    {}
func (*LogItemQueryMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4756a0aec8b9d44, []int{2}
}

func (m *LogItemQueryMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogItemQueryMessage.Unmarshal(m, b)
}
func (m *LogItemQueryMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogItemQueryMessage.Marshal(b, m, deterministic)
}
func (m *LogItemQueryMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogItemQueryMessage.Merge(m, src)
}
func (m *LogItemQueryMessage) XXX_Size() int {
	return xxx_messageInfo_LogItemQueryMessage.Size(m)
}
func (m *LogItemQueryMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LogItemQueryMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LogItemQueryMessage proto.InternalMessageInfo

func (m *LogItemQueryMessage) GetLogMessagesAggregated() []*LogMessageAggregated {
	if m != nil {
		return m.LogMessagesAggregated
	}
	return nil
}

func init() {
	proto.RegisterType((*ImageMessage)(nil), "stats.ImageMessage")
	proto.RegisterType((*LogMessageAggregated)(nil), "stats.LogMessageAggregated")
	proto.RegisterType((*LogItemQueryMessage)(nil), "stats.LogItemQueryMessage")
}

func init() { proto.RegisterFile("stats.proto", fileDescriptor_b4756a0aec8b9d44) }

var fileDescriptor_b4756a0aec8b9d44 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xdd, 0x86, 0x16, 0x3b, 0x0d, 0x28, 0x53, 0x95, 0x10, 0x3d, 0x2c, 0x39, 0xe5, 0xd4,
	0x43, 0x7d, 0x82, 0x50, 0x21, 0x14, 0xda, 0x43, 0xd7, 0x27, 0x58, 0x71, 0x98, 0x5c, 0xd2, 0x95,
	0xdd, 0xe9, 0xa1, 0x8f, 0xea, 0xdb, 0x48, 0xd2, 0xc4, 0x88, 0xf4, 0x94, 0xdb, 0xfc, 0x33, 0x3b,
	0x3f, 0xdf, 0xfc, 0x0b, 0x8b, 0x20, 0x56, 0xc2, 0xea, 0xcb, 0x3b, 0x71, 0x38, 0x6d, 0x45, 0xa6,
	0x21, 0xde, 0xd6, 0x96, 0x69, 0x4f, 0x21, 0x58, 0x26, 0xbc, 0x87, 0xc8, 0x53, 0x48, 0x94, 0x56,
	0x79, 0x6c, 0x9a, 0x32, 0xab, 0xe0, 0x61, 0xe7, 0xb8, 0x9b, 0x17, 0xcc, 0x9e, 0xd8, 0x0a, 0x7d,
	0xe2, 0x0b, 0xcc, 0x37, 0x9e, 0x9a, 0xb2, 0x90, 0xf6, 0x7d, 0x64, 0x86, 0x06, 0x3e, 0xc1, 0xac,
	0xa8, 0xdd, 0xe9, 0x28, 0xc9, 0x44, 0xab, 0x7c, 0x62, 0x3a, 0x85, 0x29, 0xdc, 0x6e, 0xac, 0x10,
	0x3b, 0x7f, 0x4e, 0x22, 0xad, 0xf2, 0xb9, 0xf9, 0xd5, 0x59, 0x05, 0xcb, 0x9d, 0xe3, 0xad, 0x50,
	0x7d, 0x38, 0x91, 0x3f, 0xf7, 0x48, 0x07, 0x78, 0x1c, 0x00, 0xc2, 0x40, 0x90, 0x28, 0x1d, 0xe5,
	0x8b, 0xf5, 0xf3, 0xea, 0x72, 0xd6, 0x35, 0x48, 0x73, 0x7d, 0x73, 0xfd, 0xad, 0x60, 0xfa, 0xde,
	0x6c, 0x61, 0x01, 0x71, 0x49, 0xb2, 0x77, 0x47, 0xa9, 0x9a, 0x06, 0xa6, 0x83, 0xdb, 0x7f, 0x90,
	0x74, 0xd9, 0xcd, 0xfe, 0x06, 0x96, 0xdd, 0xe0, 0x1b, 0xdc, 0x95, 0x24, 0xfd, 0x15, 0x63, 0x5d,
	0x4a, 0xc0, 0x1e, 0xe4, 0x12, 0xd5, 0x48, 0xa3, 0x8f, 0x59, 0xfb, 0xbf, 0xaf, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xc0, 0x75, 0xb7, 0xfa, 0xee, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatsClient is the client API for Stats service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatsClient interface {
	GetMonthStat(ctx context.Context, in *LogItemQueryMessage, opts ...grpc.CallOption) (*ImageMessage, error)
	GetCategoryStat(ctx context.Context, in *LogItemQueryMessage, opts ...grpc.CallOption) (*ImageMessage, error)
	GetMonthAmountStat(ctx context.Context, in *LogItemQueryMessage, opts ...grpc.CallOption) (*ImageMessage, error)
}

type statsClient struct {
	cc *grpc.ClientConn
}

func NewStatsClient(cc *grpc.ClientConn) StatsClient {
	return &statsClient{cc}
}

func (c *statsClient) GetMonthStat(ctx context.Context, in *LogItemQueryMessage, opts ...grpc.CallOption) (*ImageMessage, error) {
	out := new(ImageMessage)
	err := c.cc.Invoke(ctx, "/stats.Stats/GetMonthStat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) GetCategoryStat(ctx context.Context, in *LogItemQueryMessage, opts ...grpc.CallOption) (*ImageMessage, error) {
	out := new(ImageMessage)
	err := c.cc.Invoke(ctx, "/stats.Stats/GetCategoryStat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) GetMonthAmountStat(ctx context.Context, in *LogItemQueryMessage, opts ...grpc.CallOption) (*ImageMessage, error) {
	out := new(ImageMessage)
	err := c.cc.Invoke(ctx, "/stats.Stats/GetMonthAmountStat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServer is the server API for Stats service.
type StatsServer interface {
	GetMonthStat(context.Context, *LogItemQueryMessage) (*ImageMessage, error)
	GetCategoryStat(context.Context, *LogItemQueryMessage) (*ImageMessage, error)
	GetMonthAmountStat(context.Context, *LogItemQueryMessage) (*ImageMessage, error)
}

// UnimplementedStatsServer can be embedded to have forward compatible implementations.
type UnimplementedStatsServer struct {
}

func (*UnimplementedStatsServer) GetMonthStat(ctx context.Context, req *LogItemQueryMessage) (*ImageMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthStat not implemented")
}
func (*UnimplementedStatsServer) GetCategoryStat(ctx context.Context, req *LogItemQueryMessage) (*ImageMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategoryStat not implemented")
}
func (*UnimplementedStatsServer) GetMonthAmountStat(ctx context.Context, req *LogItemQueryMessage) (*ImageMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthAmountStat not implemented")
}

func RegisterStatsServer(s *grpc.Server, srv StatsServer) {
	s.RegisterService(&_Stats_serviceDesc, srv)
}

func _Stats_GetMonthStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogItemQueryMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetMonthStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stats.Stats/GetMonthStat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetMonthStat(ctx, req.(*LogItemQueryMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_GetCategoryStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogItemQueryMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetCategoryStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stats.Stats/GetCategoryStat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetCategoryStat(ctx, req.(*LogItemQueryMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_GetMonthAmountStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogItemQueryMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetMonthAmountStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stats.Stats/GetMonthAmountStat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetMonthAmountStat(ctx, req.(*LogItemQueryMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Stats_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stats.Stats",
	HandlerType: (*StatsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMonthStat",
			Handler:    _Stats_GetMonthStat_Handler,
		},
		{
			MethodName: "GetCategoryStat",
			Handler:    _Stats_GetCategoryStat_Handler,
		},
		{
			MethodName: "GetMonthAmountStat",
			Handler:    _Stats_GetMonthAmountStat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats.proto",
}
